package jwt

import (
	"errors"
	"time"

	"github.com/golang-jwt/jwt/v5"
)

// Claims is the custom JWT claims struct.
type Claims struct {
	UserID   string `json:"user_id"`
	Username string `json:"username"`
	RoleID   string `json:"role_id"`
	jwt.RegisteredClaims
}

// Manager handles JWT generation and parsing. Tokens generated by Manager are
// meant to be short-lived ACCESS tokens (minutes, not hours/days) — session
// longevity comes from the separate opaque refresh token in pkg/refreshtoken,
// which can be revoked; a JWT cannot be revoked before it expires.
type Manager struct {
	secret []byte
	ttl    time.Duration
}

// New creates a new JWT Manager. ttl is the access token lifetime.
func New(secret string, ttl time.Duration) *Manager {
	return &Manager{
		secret: []byte(secret),
		ttl:    ttl,
	}
}

// Generate creates a signed JWT token for the given user.
func (m *Manager) Generate(userID, username, roleID string) (string, time.Time, error) {
	expiredAt := time.Now().Add(m.ttl)

	claims := &Claims{
		UserID:   userID,
		Username: username,
		RoleID:   roleID,
		RegisteredClaims: jwt.RegisteredClaims{
			ExpiresAt: jwt.NewNumericDate(expiredAt),
			IssuedAt:  jwt.NewNumericDate(time.Now()),
		},
	}

	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	signed, err := token.SignedString(m.secret)
	if err != nil {
		return "", time.Time{}, err
	}
	return signed, expiredAt, nil
}

// Parse validates a token string and returns its claims.
func (m *Manager) Parse(tokenString string) (*Claims, error) {
	token, err := jwt.ParseWithClaims(tokenString, &Claims{}, func(t *jwt.Token) (interface{}, error) {
		if _, ok := t.Method.(*jwt.SigningMethodHMAC); !ok {
			return nil, errors.New("unexpected signing method")
		}
		return m.secret, nil
	})

	if err != nil {
		return nil, err
	}

	claims, ok := token.Claims.(*Claims)
	if !ok || !token.Valid {
		return nil, errors.New("invalid token")
	}
	return claims, nil
}
